# Generated by Django 5.2.7 on 2025-12-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_land'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='title',
            new_name='farm_name',
        ),
        migrations.RemoveField(
            model_name='land',
            name='size',
        ),
        migrations.AddField(
            model_name='land',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='soil_type',
            field=models.CharField(choices=[('black', 'Black Soil'), ('red', 'Red Soil'), ('alluvial', 'Alluvial Soil'), ('sandy', 'Sandy Soil')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='suitable_for',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('both', 'Both')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_photos/')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.land')),
            ],
        ),
    ]
