# Generated by Django 5.2.7 on 2025-12-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_title_land_farm_name_remove_land_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrequest',
            name='land_title',
        ),
        migrations.AddField(
            model_name='landrequest',
            name='land',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.land'),
            preserve_default=False,
        ),
    ]
